### ISSUE TITLE
2.4.0 crashes when connecting on MIUI 12 device

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/android-app#41] opened 2021-04-16 17:58 UTC
# Bug report

## Describe your environment

* Device: MI Pocophone F1 USA Xiomi
* OS name and version: MIUI 12
* IVPN app version: 2.4.0
  
## Describe the problem

The IVPN App for Android crashes when initiating a VPN connection soon after launching the app.

It is possible to open the app and check/adjust settings without crashing.  It also seems possible to launch the app, wait for three minutes, then connect without crashing.

### Steps to reproduce:

1. Launch the IVPN App.
2. Connect via OpenVPN (single-and Multi-hop) or WireGuard.
  
### Observed Results:

Crash logging is enabled, but no logs are received.

Phone reports that IVPN app keeps stopping. If app is open it just disappears and phone app launcher screen appears.
  
### Expected Results:

The app connects and operates normally.  No issues were present on the same device with 2.3.0 site APK.
  
### Relevant Code:

n/a

**Comment by ivpn786** [comment] 2021-04-17 10:12
I also have one Mi device. Crashed in same way only in case of Mock location on. Not able to get logs but my phone generated a report to send to MI. I can send that report if you desire.

**Comment by AlexKorvin** [comment] 2021-04-19 08:58
@jordan-ivpn I think this issue related to Mock Location logic. 

@ivpn786 Thanks for details.

**Comment by AlexKorvin** [comment] 2021-04-19 09:10
> I also have one Mi device. Crashed in same way only in case of Mock location on. Not able to get logs but my phone generated a report to send to MI. I can send that report if you desire.

Could you please provide the report? It'll be very helpful.

**Comment by ivpn786** [comment] 2021-04-19 10:23
java.lang.IllegalArgumentException: Provider "gps" already exists
	at android.os.Parcel.createException(Parcel.java:2078)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.location.ILocationManager$Stub$Proxy.addTestProvider(ILocationManager.java:2022)
	at android.location.LocationManager.addTestProvider(LocationManager.java:1477)
	at net.ivpn.client.ui.mocklocation.MockLocationController.addTestProviders(MockLocationController.kt:154)
	at net.ivpn.client.ui.mocklocation.MockLocationController.mockLocationWith(MockLocationController.kt:109)
	at net.ivpn.client.ui.mocklocation.MockLocationController.mock(MockLocationController.kt:104)
	at net.ivpn.client.vpn.GlobalBehaviorController.onVpnConnected(GlobalBehaviorController.java:381)
	at net.ivpn.client.vpn.GlobalBehaviorController.updateVpnConnectionState(GlobalBehaviorController.java:342)
	at net.ivpn.client.vpn.controller.VpnBehaviorController.updateVpnConnectionState(VpnBehaviorController.java:127)
	at net.ivpn.client.vpn.controller.OpenVpnBehavior.onReceiveConnectionStatus(OpenVpnBehavior.java:438)
	at net.ivpn.client.vpn.controller.OpenVpnBehavior.access$600(OpenVpnBehavior.java:72)
	at net.ivpn.client.vpn.controller.OpenVpnBehavior$3.onReceive(OpenVpnBehavior.java:280)
	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.LocationManagerService.addTestProvider(LocationManagerService.java:3649)
	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:958)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)



This is all in report.

**Comment by gorkapernas** [comment] 2021-04-19 16:11
This issue seems to be related to https://github.com/ivpn/android-app/issues/43

We have a new beta version 2.4.1 where the crash should not happen.  We found out that the crash might be related to Android 10 devices, on lower or higher Android versions, the crash is not reproducible and the Mock Location feature works as expected.

@ivpn786 please let us know if the crash is fixed on your end once we release the new IVPN version.

**Comment by ivpn786** [comment] 2021-04-20 09:57
Thank you for quick fix.

**Comment by ivpn786** [comment] 2021-04-22 12:07
Fixed with 2.4.1 for me.

**Closed** 2021-08-16 06:31 UTC
Labels: priority: critical
